baseurl: ""
url: "https://felixhammerl.com"
title: "Felix Hammerl"
desc: "Confessions of a software developer."

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
